# Generated by Django 4.2.8 on 2024-01-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='contact_mail_field_data',
            field=models.EmailField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='last_visit_data',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='reg_data',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='short_name',
            field=models.CharField(null=True, max_length=30),
        ),
    ]
